- pipeline.id: beats-processing
  path.config: /usr/share/logstash/pipeline/beats.cfg
- pipeline.id: oracle-processing
  path.config: /usr/share/logstash/pipeline/orasession.cfg
- pipeline.id: fallback-processing
  path.config: /usr/share/logstash/pipeline/fallback.cfg